openapi: 3.0.0
tags:
  - name: User Associated Graphs
get:
  
  description: Sends list of associated graphs
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error