CREATE TABLE IF NOT EXISTS Users ( 
	Username TEXT  NOT NULL PRIMARY KEY, 
	Apikey TEXT  NOT NULL
); 

CREATE TABLE IF NOT EXISTS Graphs (
      GraphID INTEGER NOT NULL PRIMARY KEY,
      Name TEXT NOT NULL,
      Version INTEGER NOT NULL,
      Username TEXT NOT NULL
);
